### ISSUE TITLE
test() in recognizer.py not working properly

### ISSUE THREAD

**Issue by Aditya718** [satinder147/Face_recognition_attendance_system#8]
File "recognizer.py", line 35, in <module>
    test()
  File "recognizer.py", line 28, in test
    test_run=e.calculate(test_run)
  File "C:\Users\Aditya\Attendance-using-Face-master\embedding.py", line 7, in calculate
    return self.model.predict(img)[0]
  File "C:\Users\Aditya\Anaconda3\envs\myenv\lib\site-packages\keras\engine\training.py", line 1169, in predict
    steps=steps)
  File "C:\Users\Aditya\Anaconda3\envs\myenv\lib\site-packages\keras\engine\training_arrays.py", line 294, in predict_loop
    batch_outs = f(ins_batch)
  File "C:\Users\Aditya\Anaconda3\envs\myenv\lib\site-packages\keras\backend\tensorflow_backend.py", line 2715, in __call__
    return self._call(inputs)
  File "C:\Users\Aditya\Anaconda3\envs\myenv\lib\site-packages\keras\backend\tensorflow_backend.py", line 2675, in _call
    fetched = self._callable_fn(*array_vals)
  File "C:\Users\Aditya\Anaconda3\envs\myenv\lib\site-packages\tensorflow\python\client\session.py", line 1439, in __call__
    run_metadata_ptr)
  File "C:\Users\Aditya\Anaconda3\envs\myenv\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.UnknownError: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
         [[{{node Conv2d_1a_3x3/convolution}} = Conv2D[T=DT_FLOAT, _class=["loc:@Conv2d_1a_3x3_BatchNorm/cond/FusedBatchNorm/Switch"], data_format="NCHW", dilations=[1, 1, 1, 1], padding="VALID", strides=[1, 1, 2, 2], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](Conv2d_1a_3x3/convolution-0-TransposeNHWCToNCHW-LayoutOptimizer, Conv2d_1a_3x3/kernel/read)]]
         [[{{node Bottleneck_BatchNorm/cond/Merge/_4101}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="e

**Comment by shiva13425** [comment]
hi @Aditya718 
   have you successfully run the command trainer.py? if so kindly give me a suggesstion

**Comment by Aditya718** [comment]
Yes I was able to solve the issue

**Comment by Aditya718** [comment]
What is the problem that you are facing?

**Comment by Aditya718** [comment]
@shiva13425
